//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBook_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRIENDS_TABLE
    {
        public int ID { get; set; }
        public int USER_ID { get; set; }
        public int FRIEND_ID { get; set; }
        public string REQUEST { get; set; }
        public string BLOCKED { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    
        public virtual USER_TABLE USER_TABLE { get; set; }
        public virtual USER_TABLE USER_TABLE1 { get; set; }
    }
}
