//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBook_EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class LIKES_TABLE
    {
        public int ID { get; set; }
        public int POST_ID { get; set; }
        public int LIKED_BY { get; set; }
    
        public virtual USER_TABLE USER_TABLE { get; set; }
        public virtual POST_TABLE POST_TABLE { get; set; }
    }
}
