//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBook_EF_Library
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PasteBookDB_AYENGEntities : DbContext
    {
        public PasteBookDB_AYENGEntities()
            : base("name=PasteBookDB_AYENGEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMENTS_TABLE> COMMENTS_TABLE { get; set; }
        public virtual DbSet<FRIENDS_TABLE> FRIENDS_TABLE { get; set; }
        public virtual DbSet<LIKES_TABLE> LIKES_TABLE { get; set; }
        public virtual DbSet<NOTIFICATION_TABLE> NOTIFICATION_TABLE { get; set; }
        public virtual DbSet<POST_TABLE> POST_TABLE { get; set; }
        public virtual DbSet<REF_COUNTRY> REF_COUNTRY { get; set; }
        public virtual DbSet<USER_TABLE> USER_TABLE { get; set; }
    }
}
