//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasteBook_EF_Library
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER_TABLE()
        {
            this.COMMENTS_TABLE = new HashSet<COMMENTS_TABLE>();
            this.FRIENDS_TABLE = new HashSet<FRIENDS_TABLE>();
            this.FRIENDS_TABLE1 = new HashSet<FRIENDS_TABLE>();
            this.LIKES_TABLE = new HashSet<LIKES_TABLE>();
            this.NOTIFICATION_TABLE = new HashSet<NOTIFICATION_TABLE>();
            this.NOTIFICATION_TABLE1 = new HashSet<NOTIFICATION_TABLE>();
            this.POST_TABLE = new HashSet<POST_TABLE>();
            this.POST_TABLE1 = new HashSet<POST_TABLE>();
        }
    
        public int ID { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string SALT { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public System.DateTime BIRTHDAY { get; set; }
        public Nullable<int> COUNTRY_ID { get; set; }
        public string MOBILE_NO { get; set; }
        public string GENDER { get; set; }
        public byte[] PROFILE_PIC { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string ABOUT_ME { get; set; }
        public string EMAIL_ADDRESS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS_TABLE> COMMENTS_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRIENDS_TABLE> FRIENDS_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FRIENDS_TABLE> FRIENDS_TABLE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LIKES_TABLE> LIKES_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION_TABLE> NOTIFICATION_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTIFICATION_TABLE> NOTIFICATION_TABLE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST_TABLE> POST_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POST_TABLE> POST_TABLE1 { get; set; }
        public virtual REF_COUNTRY REF_COUNTRY { get; set; }
    }
}
